<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SiegeProfileManager</AssemblyName>
    <RootNamespace>SPM.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <Version>3.5.0</Version>
    <ApplicationIcon>Assets/icon.ico</ApplicationIcon>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>none</DebugType>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.5" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.5" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.5" />
    <ProjectReference Include="../Core/SPM.Core.csproj" />
    <AvaloniaResource Include="Assets/icon.png" />
    <EmbeddedResource Include="../../siege_profile_manager.lua" LogicalName="siege_profile_manager.lua" />
  </ItemGroup>
</Project>
