namespace SPM.Core;

/// <summary>Generated from siege_profile_manager.lua: weapons, operators and the on-screen selector layout.</summary>
public sealed record WeaponInfo(string Id, string Kind, string[] Scopes, string[] Barrels, string[] Grips);
public sealed record OperatorInfo(string Name, string Side, string[] Primary, string[] Secondary, string DefaultPrimary, string DefaultSecondary);

public static class GameData
{
    public static readonly WeaponInfo[] Weapons =
    {
        new("M4", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("M249", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("SR-25", "primary", new[] { "TELESCOPIC A", "TELESCOPIC B", "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("M590A1", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new("L85A2", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("AR33", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("PMR90A2", "primary", Array.Empty<string>(), new[] { "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("G36C", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("R4-C", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("556XI", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("M1014", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new("F2", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("417", "primary", new[] { "TELESCOPIC A", "TELESCOPIC B", "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("SG-CQB", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "NONE" }, new[] { "HORIZONTAL", "VERTICAL" }),
        new("OTS-03", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("6P41", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("AK-12", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("AUG A2", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "NONE" }),
        new("552 COMMANDO", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("G8A1", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("C8-SFW", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "NONE" }),
        new("CAMRS", "primary", new[] { "TELESCOPIC A", "TELESCOPIC B", "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("MK17 CQB", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("PARA-308", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("TYPE-89", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("SUPERNOVA", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL" }),
        new("C7E", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("PDW9", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("ITA12L", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new("T-95 LSW", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("SIX12", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new("LMG-E", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("M762", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("XK23", "primary", Array.Empty<string>(), new[] { "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("MK 14 EBR", "primary", new[] { "TELESCOPIC A", "TELESCOPIC B", "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("BOSG.12.2", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("V308", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("SPEAR .308", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("SASG-12", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("AR-15.50", "primary", new[] { "TELESCOPIC A", "TELESCOPIC B", "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("AK-74M", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("ARX200", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("F90", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("M249 SAW", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("FMG-9", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "NONE" }),
        new("SIX12 SD", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new("CSRX 300", "primary", new[] { "CUSTOM SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new("SC3000K", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("MP7", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "NONE" }),
        new("POF-9", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("COMMANDO 9", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("M870", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new("TCSG12", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("MP5K", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "NONE" }),
        new("UMP45", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("MP5", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("P90", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "NONE" }),
        new("9X19VSN", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("DP27", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "REFLEX D", "IRON SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new("416-C", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("SUPER 90", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new("9MM C1", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("MPX", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("SPAS-12", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new("M12", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("SPAS-15", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new("MP5SD", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("VECTOR .45 ACP", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("T-5 SMG", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("SCORPION EVO 3 A1", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("FO-12", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("K1A", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("ALDA 5.56", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "HORIZONTAL", "VERTICAL" }),
        new("ACS12", "primary", new[] { "MAGNIFIED A", "MAGNIFIED B", "MAGNIFIED C", "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("MX4 STORM", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("AUG A3", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("P10 RONI", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("UZK50GI", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("PCX-33", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("GLAIVE-12", "primary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("5.7 USG", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "NONE" }),
        new("ITA12S", "secondary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new("REAPER MK2", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "NONE" }),
        new("P226 MK 25", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "NONE" }),
        new("M45 MEUSOC", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "NONE" }),
        new("P9", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "NONE" }),
        new("LFP586", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new("PMM", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "NONE" }),
        new("GONNE-6", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new("BEARING 9", "secondary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "NONE" }),
        new("GSH-18", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "NONE" }),
        new("P12", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "NONE" }),
        new("MK1 9MM", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "NONE" }),
        new("PRB92", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "NONE" }),
        new("P229", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "NONE" }),
        new("USP40", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "NONE" }),
        new("Q-929", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "NONE" }),
        new("RG15", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "NONE" }),
        new("SMG-12", "secondary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("C75 AUTO", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "SUPPRESSOR", "NONE" }, new[] { "NONE" }),
        new("1911 TACOPS", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "NONE" }),
        new(".44 MAG SEMI-AUTO", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new("SUPER SHORTY", "secondary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new("SDP 9MM", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new("D-50", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new("SMG-11", "secondary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "HORIZONTAL", "VERTICAL", "ANGLED" }),
        new("SPSMG9", "secondary", new[] { "RED DOT A", "RED DOT B", "RED DOT C", "HOLO A", "HOLO B", "HOLO C", "HOLO D", "REFLEX A", "REFLEX B", "REFLEX C", "IRON SIGHT" }, new[] { "FLASH HIDER", "COMPENSATOR", "MUZZLE BRAKE", "SUPPRESSOR", "EXTENDED BARREL", "NONE" }, new[] { "NONE" }),
        new("BAILIFF 410", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new(".44 VENDETTA", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
        new("TACIT .45", "secondary", Array.Empty<string>(), new[] { "NONE" }, new[] { "NONE" }),
        new("P-10C", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "NONE" }),
        new("KERATOS .357", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "MUZZLE BRAKE", "SUPPRESSOR", "NONE" }, new[] { "NONE" }),
        new("LUISON", "secondary", new[] { "CUSTOM SIGHT" }, new[] { "NONE" }, new[] { "NONE" }),
    };

    public static readonly OperatorInfo[] Operators =
    {
        new("Striker", "attackers", new[] { "M4", "M249", "SR-25" }, new[] { "5.7 USG", "ITA12S" }, "M4", "5.7 USG"),
        new("Sledge", "attackers", new[] { "M590A1", "L85A2" }, new[] { "REAPER MK2", "P226 MK 25" }, "L85A2", "REAPER MK2"),
        new("Thatcher", "attackers", new[] { "AR33", "L85A2", "PMR90A2", "M590A1" }, new[] { "P226 MK 25" }, "AR33", "P226 MK 25"),
        new("Ash", "attackers", new[] { "G36C", "R4-C" }, new[] { "M45 MEUSOC", "5.7 USG" }, "R4-C", "M45 MEUSOC"),
        new("Thermite", "attackers", new[] { "556XI", "M1014" }, new[] { "M45 MEUSOC", "5.7 USG", "ITA12S" }, "556XI", "M45 MEUSOC"),
        new("Twitch", "attackers", new[] { "F2", "417", "SG-CQB" }, new[] { "P9", "LFP586" }, "F2", "P9"),
        new("Montagne", "attackers", Array.Empty<string>(), new[] { "P9", "LFP586" }, "", "P9"),
        new("Glaz", "attackers", new[] { "OTS-03" }, new[] { "PMM", "GONNE-6", "BEARING 9" }, "OTS-03", "PMM"),
        new("Fuze", "attackers", new[] { "6P41", "AK-12" }, new[] { "PMM", "GSH-18" }, "6P41", "PMM"),
        new("Blitz", "attackers", Array.Empty<string>(), new[] { "P12" }, "", "P12"),
        new("IQ", "attackers", new[] { "AUG A2", "552 COMMANDO", "G8A1" }, new[] { "P12" }, "AUG A2", "P12"),
        new("Buck", "attackers", new[] { "C8-SFW", "CAMRS" }, new[] { "MK1 9MM" }, "C8-SFW", "MK1 9MM"),
        new("Blackbeard", "attackers", new[] { "MK17 CQB", "SR-25" }, Array.Empty<string>(), "MK17 CQB", ""),
        new("Capitao", "attackers", new[] { "PARA-308", "M249", "PMR90A2" }, new[] { "PRB92", "GONNE-6" }, "PARA-308", "PRB92"),
        new("Hibana", "attackers", new[] { "TYPE-89", "SUPERNOVA", "PMR90A2" }, new[] { "P229", "BEARING 9" }, "TYPE-89", "P229"),
        new("Jackal", "attackers", new[] { "C7E", "PDW9", "ITA12L" }, new[] { "USP40", "ITA12S" }, "C7E", "USP40"),
        new("Ying", "attackers", new[] { "T-95 LSW", "SIX12" }, new[] { "Q-929", "REAPER MK2" }, "T-95 LSW", "Q-929"),
        new("Zofia", "attackers", new[] { "LMG-E", "M762" }, new[] { "RG15" }, "M762", "RG15"),
        new("Dokkaebi", "attackers", new[] { "XK23", "MK 14 EBR", "BOSG.12.2" }, new[] { "SMG-12", "C75 AUTO", "GONNE-6" }, "XK23", "SMG-12"),
        new("Lion", "attackers", new[] { "V308", "417", "SG-CQB" }, new[] { "LFP586", "P9" }, "V308", "LFP586"),
        new("Finka", "attackers", new[] { "SPEAR .308", "6P41", "SASG-12" }, new[] { "PMM", "GSH-18" }, "SPEAR .308", "PMM"),
        new("Maverick", "attackers", new[] { "AR-15.50", "M4" }, new[] { "1911 TACOPS", "REAPER MK2" }, "AR-15.50", "1911 TACOPS"),
        new("Nomad", "attackers", new[] { "AK-74M", "ARX200" }, new[] { ".44 MAG SEMI-AUTO", "PRB92" }, "AK-74M", ".44 MAG SEMI-AUTO"),
        new("Gridlock", "attackers", new[] { "F90", "M249 SAW" }, new[] { "SUPER SHORTY", "SDP 9MM" }, "F90", "SUPER SHORTY"),
        new("Nokk", "attackers", new[] { "FMG-9", "SIX12 SD", "PMR90A2" }, new[] { "5.7 USG", "D-50" }, "FMG-9", "5.7 USG"),
        new("Amaru", "attackers", new[] { "G8A1", "SUPERNOVA" }, new[] { "SMG-11", "ITA12S", "GONNE-6" }, "G8A1", "SMG-11"),
        new("Kali", "attackers", new[] { "CSRX 300" }, new[] { "SPSMG9", "C75 AUTO", "P226 MK 25" }, "CSRX 300", "SPSMG9"),
        new("Iana", "attackers", new[] { "ARX200", "G36C" }, new[] { "MK1 9MM", "GONNE-6" }, "ARX200", "MK1 9MM"),
        new("Ace", "attackers", new[] { "AK-12", "M1014" }, new[] { "P9" }, "AK-12", "P9"),
        new("Zero", "attackers", new[] { "SC3000K", "MP7" }, new[] { "5.7 USG", "GONNE-6" }, "SC3000K", "5.7 USG"),
        new("Flores", "attackers", new[] { "AR33", "SR-25", "T-95 LSW" }, new[] { "GSH-18" }, "AR33", "GSH-18"),
        new("Osa", "attackers", new[] { "556XI", "PDW9" }, new[] { "PMM" }, "556XI", "PMM"),
        new("Sens", "attackers", new[] { "POF-9", "417", "XK23" }, new[] { "SDP 9MM" }, "POF-9", "SDP 9MM"),
        new("Grim", "attackers", new[] { "552 COMMANDO", "SG-CQB" }, new[] { "P229", "BAILIFF 410" }, "552 COMMANDO", "P229"),
        new("Brava", "attackers", new[] { "PARA-308", "CAMRS" }, new[] { "SUPER SHORTY", "USP40" }, "PARA-308", "SUPER SHORTY"),
        new("Ram", "attackers", new[] { "R4-C", "LMG-E" }, new[] { "MK1 9MM" }, "R4-C", "MK1 9MM"),
        new("Deimos", "attackers", new[] { "AK-74M", "M590A1" }, new[] { ".44 VENDETTA" }, "AK-74M", ".44 VENDETTA"),
        new("Rauora", "attackers", new[] { "417", "M249", "XK23" }, new[] { "REAPER MK2", "GSH-18" }, "417", "REAPER MK2"),
        new("Solid Snake", "attackers", new[] { "F2", "PMR90A2" }, new[] { "TACIT .45" }, "F2", "TACIT .45"),
        new("Sentry", "defenders", new[] { "COMMANDO 9", "M870", "TCSG12" }, new[] { "C75 AUTO", "SUPER SHORTY" }, "COMMANDO 9", "C75 AUTO"),
        new("Smoke", "defenders", new[] { "FMG-9", "M590A1" }, new[] { "P226 MK 25", "SMG-11" }, "FMG-9", "P226 MK 25"),
        new("Mute", "defenders", new[] { "MP5K", "M590A1" }, new[] { "P226 MK 25", "SMG-11" }, "M590A1", "SMG-11"),
        new("Castle", "defenders", new[] { "UMP45", "M1014" }, new[] { "5.7 USG", "SUPER SHORTY", "M45 MEUSOC" }, "UMP45", "5.7 USG"),
        new("Pulse", "defenders", new[] { "M1014", "UMP45" }, new[] { "REAPER MK2", "M45 MEUSOC", "5.7 USG" }, "UMP45", "REAPER MK2"),
        new("Doc", "defenders", new[] { "SG-CQB", "MP5", "P90" }, new[] { "P9", "LFP586", "BAILIFF 410" }, "MP5", "P9"),
        new("Rook", "defenders", new[] { "P90", "MP5", "SG-CQB" }, new[] { "LFP586", "P9", "REAPER MK2" }, "P90", "LFP586"),
        new("Kapkan", "defenders", new[] { "9X19VSN", "SASG-12" }, new[] { "PMM", "GSH-18" }, "9X19VSN", "PMM"),
        new("Tachanka", "defenders", new[] { "DP27", "9X19VSN" }, new[] { "GSH-18", "PMM", "BEARING 9" }, "DP27", "GSH-18"),
        new("Jager", "defenders", new[] { "M870", "416-C" }, new[] { "P12", "P-10C" }, "416-C", "P12"),
        new("Bandit", "defenders", new[] { "MP7", "M870" }, new[] { "KERATOS .357", "P12" }, "MP7", "KERATOS .357"),
        new("Frost", "defenders", new[] { "SUPER 90", "9MM C1" }, new[] { "MK1 9MM", "ITA12S" }, "9MM C1", "MK1 9MM"),
        new("Valkyrie", "defenders", new[] { "MPX", "SPAS-12" }, new[] { "D-50" }, "MPX", "D-50"),
        new("Caveira", "defenders", new[] { "M12", "SPAS-15" }, new[] { "LUISON" }, "M12", "LUISON"),
        new("Echo", "defenders", new[] { "SUPERNOVA", "MP5SD" }, new[] { "P229", "BEARING 9" }, "MP5SD", "P229"),
        new("Mira", "defenders", new[] { "VECTOR .45 ACP", "ITA12L" }, new[] { "USP40", "ITA12S" }, "VECTOR .45 ACP", "USP40"),
        new("Lesion", "defenders", new[] { "SIX12 SD", "T-5 SMG" }, new[] { "Q-929" }, "T-5 SMG", "Q-929"),
        new("Ela", "defenders", new[] { "SCORPION EVO 3 A1", "FO-12" }, new[] { "RG15" }, "SCORPION EVO 3 A1", "RG15"),
        new("Vigil", "defenders", new[] { "K1A", "BOSG.12.2" }, new[] { "C75 AUTO", "SMG-12" }, "K1A", "C75 AUTO"),
        new("Maestro", "defenders", new[] { "ALDA 5.56", "ACS12" }, new[] { "BAILIFF 410", "KERATOS .357" }, "ALDA 5.56", "BAILIFF 410"),
        new("Alibi", "defenders", new[] { "MX4 STORM", "ACS12" }, new[] { "KERATOS .357", "BAILIFF 410" }, "MX4 STORM", "KERATOS .357"),
        new("Clash", "defenders", Array.Empty<string>(), new[] { "SUPER SHORTY", "SPSMG9", "P-10C" }, "", "SUPER SHORTY"),
        new("Kaid", "defenders", new[] { "AUG A3", "TCSG12" }, new[] { ".44 MAG SEMI-AUTO", "LFP586" }, "AUG A3", ".44 MAG SEMI-AUTO"),
        new("Mozzie", "defenders", new[] { "COMMANDO 9", "P10 RONI" }, new[] { "SDP 9MM", "SUPER SHORTY" }, "COMMANDO 9", "SDP 9MM"),
        new("Warden", "defenders", new[] { "M590A1", "MPX" }, new[] { "P-10C", "SMG-12" }, "M590A1", "SMG-12"),
        new("Goyo", "defenders", new[] { "VECTOR .45 ACP", "TCSG12" }, new[] { "P229" }, "VECTOR .45 ACP", "P229"),
        new("Wamai", "defenders", new[] { "AUG A2", "MP5K" }, new[] { "KERATOS .357", "P12", "SUPER SHORTY" }, "AUG A2", "KERATOS .357"),
        new("Oryx", "defenders", new[] { "T-5 SMG", "SPAS-12" }, new[] { "BAILIFF 410", "USP40", "REAPER MK2" }, "T-5 SMG", "BAILIFF 410"),
        new("Melusi", "defenders", new[] { "MP5", "SUPER 90" }, new[] { "RG15", "ITA12S" }, "MP5", "RG15"),
        new("Aruni", "defenders", new[] { "P10 RONI", "MK 14 EBR" }, new[] { "PRB92" }, "P10 RONI", "PRB92"),
        new("Thunderbird", "defenders", new[] { "SPEAR .308", "SPAS-15" }, new[] { "Q-929", "BEARING 9", "ITA12S" }, "SPEAR .308", "Q-929"),
        new("Thorn", "defenders", new[] { "UZK50GI", "M870" }, new[] { "1911 TACOPS", "C75 AUTO" }, "UZK50GI", "1911 TACOPS"),
        new("Azami", "defenders", new[] { "9X19VSN", "ACS12" }, new[] { "D-50" }, "9X19VSN", "D-50"),
        new("Solis", "defenders", new[] { "P90", "ITA12L" }, new[] { "SMG-11" }, "P90", "SMG-11"),
        new("Fenrir", "defenders", new[] { "MP7", "SASG-12" }, new[] { "5.7 USG" }, "MP7", "5.7 USG"),
        new("Tubarao", "defenders", new[] { "MPX", "AR-15.50" }, new[] { "P226 MK 25" }, "MPX", "P226 MK 25"),
        new("Skopos", "defenders", new[] { "PCX-33" }, new[] { "P229" }, "PCX-33", "P229"),
        new("Denari", "defenders", new[] { "SCORPION EVO 3 A1", "FMG-9", "GLAIVE-12" }, new[] { "P226 MK 25" }, "SCORPION EVO 3 A1", "P226 MK 25"),
        new("Noor", "defenders", new[] { "COMMANDO 9", "ALDA 5.56" }, new[] { "1911 TACOPS", "BAILIFF 410" }, "COMMANDO 9", "1911 TACOPS"),
    };

    /// <summary>7 x 7 selector layout, row by row; null = empty tile.</summary>
    public static readonly string?[][] GridAttackers = new string?[][]
    {
        new string?[] { "Striker", "Sledge", "Thatcher", "Ash", "Thermite", "Twitch", "Montagne" },
        new string?[] { "Glaz", "Fuze", "Blitz", "IQ", "Buck", "Blackbeard", "Capitao" },
        new string?[] { "Hibana", "Jackal", "Ying", "Zofia", "Dokkaebi", "Lion", "Finka" },
        new string?[] { "Maverick", "Nomad", "Gridlock", "Nokk", "Amaru", "Kali", "Iana" },
        new string?[] { "Ace", "Zero", "Flores", "Osa", "Sens", "Grim", "Brava" },
        new string?[] { "Ram", "Deimos", "Rauora", "Solid Snake", null, null, null },
        new string?[] { null, null, null, null, null, null, null },
    };
    public static readonly string?[][] GridDefenders = new string?[][]
    {
        new string?[] { "Sentry", "Smoke", "Mute", "Castle", "Pulse", "Doc", "Rook" },
        new string?[] { "Kapkan", "Tachanka", "Jager", "Bandit", "Frost", "Valkyrie", "Caveira" },
        new string?[] { "Echo", "Mira", "Lesion", "Ela", "Vigil", "Maestro", "Alibi" },
        new string?[] { "Clash", "Kaid", "Mozzie", "Warden", "Goyo", "Wamai", "Oryx" },
        new string?[] { "Melusi", "Aruni", "Thunderbird", "Thorn", "Azami", "Solis", "Fenrir" },
        new string?[] { "Tubarao", "Skopos", "Denari", "Noor", null, null, null },
        new string?[] { null, null, null, null, null, null, null },
    };

    static Dictionary<string, WeaponInfo>? _w;
    public static WeaponInfo? Weapon(string id) { _w ??= Weapons.ToDictionary(x => x.Id, StringComparer.Ordinal); return _w.TryGetValue(id, out var v) ? v : null; }
    public static OperatorInfo? Operator(string name) => Operators.FirstOrDefault(o => string.Equals(o.Name, name, StringComparison.OrdinalIgnoreCase));
}
