using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace SPM.Core;

/// <summary>Builds the SPM_USER block the Lua reads, and merges it into the user's Lua script.</summary>
public static class LuaBlock
{
    public const string BeginMark = "-- >>> SPM_USER BEGIN";
    public const string EndMark = "-- <<< SPM_USER END <<<";
    static readonly string[] BarrelChain = { "SUPPRESSOR", "COMPENSATOR", "FLASH HIDER", "MUZZLE BRAKE", "EXTENDED BARREL", "NONE" };
    static readonly string[] GripChain = { "HORIZONTAL", "VERTICAL", "ANGLED", "NONE" };

    public static string Q(string s) => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    public static string N(double v) =>
        v == Math.Round(v) ? ((long)Math.Round(v)).ToString(CultureInfo.InvariantCulture) : v.ToString("F5", CultureInfo.InvariantCulture);

    static string List(IEnumerable<string> items) => "{ " + string.Join(", ", items.Select(Q)) + " }";

    static string SlotText(Slot? s) => s == null
        ? "{}"
        : $"{{ weapon = {Q(s.Weapon)}, scope = {Q(s.Scope)}, barrel = {Q(s.Barrel)}, grip = {Q(s.Grip)} }}";

    static string Aspect(int w, int h)
    {
        double r = (double)w / Math.Max(h, 1);
        foreach (var (name, val) in new[] { ("32:9", 32 / 9.0), ("21:9", 21 / 9.0), ("16:9", 16 / 9.0), ("16:10", 1.6), ("4:3", 4 / 3.0) })
            if (Math.Abs(r - val) < 0.08) return name;
        return $"{w}:{h}";
    }

    static IEnumerable<string> Chain(string pref, string[] baseChain)
    {
        var list = new List<string>();
        if (!string.IsNullOrEmpty(pref) && pref != "AUTO") list.Add(pref);
        list.AddRange(baseChain);
        return list;
    }

    /// <summary>The complete block text including both markers.</summary>
    public static string Build(AppConfig c, string rev)
    {
        var o = StringComparer.Ordinal;
        var g = c.Game;
        var t = new StringBuilder();
        t.Append("-- >>> SPM_USER BEGIN (generated by Siege Profile Manager; paste a new block over everything between the markers) >>>\n");
        t.Append("local SPM_USER = {\n");
        t.Append($"    rev = {Q(rev)},\n");
        t.Append($"    dpi = {N(g.Dpi)}, fov = {N(g.Fov)}, ads = {N(g.Ads)},\n");
        t.Append($"    sens = {{ h = {N(g.SensH)}, v = {N(g.SensV)} }},\n");
        t.Append($"    resolution = {{ w = {N(g.ResW)}, h = {N(g.ResH)} }},\n");
        t.Append($"    aspect = {Q(Aspect(g.ResW, g.ResH))},\n");
        t.Append("    preferred = {\n");
        t.Append($"        scope = {(c.Prefs.Scope == "AUTO" || c.Prefs.Scope == "" ? "{}" : List(new[] { c.Prefs.Scope }))},\n");
        t.Append($"        barrel = {List(Chain(c.Prefs.Barrel, BarrelChain))},\n");
        t.Append($"        grip = {List(Chain(c.Prefs.Grip, GripChain))},\n");
        t.Append("    },\n");
        t.Append($"    side = {Q(c.Side == "defenders" ? "defenders" : "attackers")},\n");
        if (c.Operator != "") t.Append($"    operator = {Q(c.Operator)},\n");
        t.Append($"    favorites = {List(c.Favorites)},\n");
        t.Append("    saved = {\n");
        foreach (var kv in c.Saved.OrderBy(k => k.Key, o))
            t.Append($"        [{Q(kv.Key)}] = {{ primary = {SlotText(kv.Value.Primary)}, secondary = {SlotText(kv.Value.Secondary)} }},\n");
        t.Append("    },\n");
        t.Append("    loadouts = {\n");
        foreach (var kv in c.Loadouts.OrderBy(k => k.Key, o))
        {
            if (kv.Value.List.Count == 0) continue;
            t.Append($"        [{Q(kv.Key)}] = {{ active = {Q(kv.Value.Active)}, list = {{\n");
            foreach (var e in kv.Value.List)
                t.Append($"            {{ name = {Q(e.Name)}, primary = {SlotText(e.Loadout.Primary)}, secondary = {SlotText(e.Loadout.Secondary)} }},\n");
            t.Append("        } },\n");
        }
        t.Append("    },\n");
        t.Append("    recoil = {\n");
        foreach (var kv in c.Learned.OrderBy(k => k.Key, o))
        {
            var p = kv.Value;
            t.Append($"        [{Q(kv.Key)}] = {{ r = {N(p.R)}, y1 = {N(p.Y1)}, y2 = {N(p.Y2)}, tym1 = {N(p.Tym1)}, tym2 = {N(p.Tym2)}, side = {N(p.Side)}, strength = {N(p.Strength)}, late = {N(p.Late)} }},\n");
        }
        t.Append("    },\n");
        t.Append("    calibration = {\n");
        foreach (var side in new[] { "attackers", "defenders" })
            if (c.Calibration.TryGetValue(side, out var cal))
                t.Append($"        {side} = {{ tlx = {N(cal.Tlx)}, tly = {N(cal.Tly)}, brx = {N(cal.Brx)}, bry = {N(cal.Bry)} }},\n");
        t.Append("    },\n");
        t.Append("    keybinds = {\n");
        foreach (var kv in c.LuaKeybinds.OrderBy(k => k.Key, o))
            t.Append($"        {kv.Key} = {{ mod = {Q(kv.Value.Mod)}, button = {kv.Value.Button} }},\n");
        t.Append("    },\n");
        t.Append("}\n");
        t.Append(EndMark + "\n");
        return t.ToString();
    }

    /// <summary>The user's whole script with the block replaced. Everything outside the markers is kept byte for byte.</summary>
    public static string? Merge(string scriptText, AppConfig c, string rev, out string error)
    {
        error = "";
        int b = scriptText.IndexOf(BeginMark, StringComparison.Ordinal);
        int e = b >= 0 ? scriptText.IndexOf(EndMark, b, StringComparison.Ordinal) : -1;
        if (b < 0 || e < 0)
        {
            error = "that Lua file has no SPM_USER markers - use the siege_profile_manager.lua that comes with the app";
            return null;
        }
        string eol = scriptText.Contains("\r\n") ? "\r\n" : "\n";
        string block = Build(c, rev).TrimEnd('\n').Replace("\n", eol);
        return scriptText[..b] + block + scriptText[(e + EndMark.Length)..];
    }

    /// <summary>Hash of the part of the config the Lua consumes: changes mean the Lua copy is out of date.</summary>
    public static string ContentHash(AppConfig c)
    {
        var body = Build(c, "0");
        return Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(body)))[..16];
    }
}
